server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${SECRET_KAFKA_HOST:localhost}:${SECRET_KAFKA_PORT:9092}
    consumer:
      group-id: "my-awesome-app"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SECRET_MAIL_USERNAME:nattkarn.dev} #don't add @gmail.com
    password: ${SECRET_MAIL_PASSWORD:kqtvwjkelsmpnwhs}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  redis:
#    host: "localhost"
#    port: 6379
#    ssl:
#      enabled: true
#
#  cache:
#    type: redis
#    redis:
#      time-to-live: 300000


  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${SECRET_DB_HOST:localhost}:${SECRET_DB_PORT:5432}/${SECRET_DB_NAME:backend}
    username: ${SECRET_DB_USERNAME:postgres}
    password: ${SECRET_DB_PASSWORD:syspass}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 25MB

---
app:
  token:
    secret: ${SECRET_JWT_SECRET:Arm@1144nb}
    issuer: BackendService
  email:
    form: nattkarn.dev@gmail.com




