spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 25MB
app:
  token:
    secret: Arm@1144nb
    issuer: BackendService




